language: scala

scala:
#   - 2.10.6
   - 2.11.11
   - 2.12.2
jdk:
  - oraclejdk7
  - oraclejdk8

matrix:
  exclude:
    - scala: 2.11.11
      jdk: oraclejdk8
    - scala: 2.12.2
      jdk: oraclejdk7

git:
  depth: 3

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y protobuf-compiler

before_script: # https://github.com/travis-ci/travis-ci/issues/7703
  - sudo chmod +x /usr/local/bin/sbt

script:
  - sbt clean coverage test

after_success:
  - sbt coverageReport coveralls