language: scala

scala:
#   - 2.10.6
#  - 2.11.12
  - 2.12.12
  - 2.13.3
jdk:
  - openjdk8

git:
  depth: 3

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y protobuf-compiler

before_script: # https://github.com/travis-ci/travis-ci/issues/7703
  - sudo chmod +x /usr/local/bin/sbt
  - sbt clean

script:
  - sbt clean "++$TRAVIS_SCALA_VERSION test" coverageAggregate

after_success:
  - sbt coveralls
