language: scala

jobs:
  include:
    - scala: 2.11.12
      jdk: openjdk8
      env: PATCH_211=true
      script:
        - sbt clean "++$TRAVIS_SCALA_VERSION test"
      after_success:
        - sbt coveralls
    - scala: 2.12.12
      jdk: openjdk8
      env: PATCH_211=false
      script:
        - sbt clean coverage "++$TRAVIS_SCALA_VERSION test" coverageAggregate
      after_success:
        - sbt coveralls
    - scala: 2.13.3
      jdk: openjdk8
      env: PATCH_211=false
      script:
        - sbt clean "++$TRAVIS_SCALA_VERSION test"

git:
  depth: 3

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y protobuf-compiler

before_script: # https://github.com/travis-ci/travis-ci/issues/7703
  - sudo chmod +x /usr/local/bin/sbt
  - sbt clean
